### ISSUE TITLE
Nps prepare fails

### ISSUE THREAD

**Issue by 28development** [ejazahm3d/fullstack-turborepo-starter#1]
Hi, I cloned this repo and ran

```
npm i -g nps
```

Afterwards I went to the root of the project's directory and ran

```
nps prepare
```

But I get following error:

```
nps prepare
nps is executing `prepare` : nps prepare.web prepare.api
nps is executing `prepare.web` : yarn
/bin/sh: yarn: command not found
The script called "prepare.web" which runs "yarn" failed with exit code 127 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "prepare" which runs "nps prepare.web prepare.api" failed with exit code 127 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
```

Any ideas about what this is related to?

**Comment by ejazahm3d** [comment]
> Ok seems like I did not install yarn globally, that seems to fix it issue, maybe the readme can be updated. I may do a PR

No worries. Thanks for bringing this to my attention. 
Pruning of dependencies for creating docker images currently doesn't work with npm. At least the last time I checked. I have mentioned it in README that it uses yarn as package manager. Maybe I should highlight it a bit more or make it part of the getting start.
