### ISSUE TITLE
Shared types from workspaces

### ISSUE THREAD

**Issue by popuguytheparrot** [ejazahm3d/fullstack-turborepo-starter#6]
Hi. How to reuse types from workspace in api nestjs? Nest js throw error cannot find module "module name"

**Comment by sluchznak** [comment]
Hello.

Try to use this instruction - https://turbo.build/repo/docs/handbook/sharing-code/internal-packages

**Comment by ejazahm3d** [comment]
I am pasting this for future reference. You can actually add "dev" and "build" scripts in package.json. That way when you run `nps dev`, it will compile the typescript code to javascript and you wouldnt get module not found error. 
```json
{
  "name": "shared",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "types": "index.js",
  "scripts": {
    "build": "tsc --build",
    "dev": "tsc --watch"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```
Make sure the types and main maps to where your JS code will eventually be compiled to.
